
.build: &build
  image: docker:latest
  before_script:
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
  script:
    - HASH=$(docker build --build-arg UBUNTU_VERSION=${UBUNTU_VERSION} -q .)
    - TAGS="${UBUNTU_VERSION} ${EXTRA_TAGS}"
    - for tag in $TAGS; do docker tag $HASH jitesoft/tesseract-ocr:${tag}; docker push jitesoft/tesseract-ocr:${tag}; done

build:ubuntu1604:
  variables:
    UBUNTU_VERSION: "16.04"
    EXTRA_TAGS: "xenial"
  <<: *build

build:ubuntu1804:
  variables:
    UBUNTU_VERSION: "18.04"
    EXTRA_TAGS: "bionic latest"
  <<: *build
